spring:
  security:
    oauth2:
      client:
        registration:
          imgur:
            client-id: e098f53069f80d6
            client-secret: 66f76092c15baf6694933411b2cef382c5b12ca6
            scope: ["read"]
            redirect-uri: http://localhost:8080/callback
            authorization-grant-type: authorization_code
            client-name: Memories

          google:
            client-id: 959112376599-6j538r20bjt37sqf1o981vl04qbc7m55.apps.googleusercontent.com
            client-secret: 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
        provider:
          imgur:
            authorization-uri: https://api.imgur.com/oauth2/authorize
            token-uri: https://api.imgur.com/oauth2/token
            user-info-uri: https://api.imgur.com/3/account/me
            user-name-attribute: url
